export { default as Button } from './Button/Button'
export { default as Input } from './Input/Input'
export { default as Image } from './Img/Img'
export { default as Switch } from './Switch/Switch'
export { default as SubHeading } from './SubHeading/SubHeading'
export { default as Text } from './Text/Text'